### ISSUE TITLE
Future structure of the package

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#10]
I imagine something like this file structure:
```
cw_nineliner_and_notepad /
    dialogs /
        RscDefines.cpp
    medevac9liner [, cas9liner, ...] /
        dialogs /
        data /
            ui /
        functions /
    functions /
        [...] a page system for the dialogs
        [...] other important functions
    config.cpp
    CfgPatches.cpp
    CfgFunctions.cpp
    XEH_preInit.sqf
    stringtable.xml
    $PREFIX$
```

**Comment by TheMysteriousVincent** [comment]
I'll update this now.

**Comment by TheMysteriousVincent** [comment]
I just want to add that the `dialogs` folder will be renamed to a more common & general name `gui`.

**Comment by Saborknight** [comment]
Shall we implement each sheet to its own PBO as @TheMysteriousVincent suggested originally? and then have the "main" PBO and "fonts" PBO?
So a structure similar to:

```
\addons
    \main
    \sheet_nineliner_cas
    \sheet_nineliner_medevac
    \sheet_fiveliner_gunship_cff
    [...]
    \fonts
```

where "main" will have all shared functions and gui elements, etc. and each sheet has only those things specific to itself. Fonts is self-explanatory.

**Comment by TheMysteriousVincent** [comment]
I like this kind of structure more but I rather would use "ui_fonts" instead of "fonts".

**Comment by TheMysteriousVincent** [comment]
Furthermore what would you add to "main"?

**Comment by Saborknight** [comment]
Currently we have:

```
\sheets
    \functions
    \gui
    \sheets_x
    [...]
    \CfgFunctions.cpp
    \CfgPatches.cpp
    \CfgVehicles.cpp
    \config.cpp
    \stringtable.xml
    \XEH_clientPreInit.sqf
```

and how I envision the structure being, taking the above into account:

```
\main
    \functions
    \gui
    \CfgFunctions.cpp
    \CfgPatches.cpp
    \CfgVehicles.cpp
    \config.cpp
    \stringtable.xml
    \XEH_clientPreInit.sqf
\sheet_adjust_fire_mission
    \data
    \functions
    \gui
    \CfgFunctions.cpp
    \CfgVehicles.cpp
    \config.cpp
    \stringtable.xml
    \XEH_clientPreInit.sqf
\sheet_x
[...]
\ui_fonts
```

**Comment by Saborknight** [comment]
The whole point of this is to make it as module based as possible for 3rd party additions to be made without being required to implement their additions into the mod itself. 

So a unit could create their own addition mod (we can provide a template for this) and have their members install our mod and their unit's version of the mod.
A contributor could add an additional PBO for each sheet they want to add to the mod itself.

**Comment by TheMysteriousVincent** [comment]
I would remove the `sheets_` prefix because either no variables or functions use the name `nln_sheet_<x>`.

**Comment by TheMysteriousVincent** [comment]
The structural work is done with 364ae759557817cc3d172bf77b3c815417bfde3c
The template for sheet packages refers to this issue #19.
