### ISSUE TITLE
Implementing TravisCI, or some other "Continual Integration" for building the mod

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#14]
**Waiting on:** #6 

---

As @TheMysteriousVincent mentioned in #6 : 

> Maybe we should also use something like TravisCI, e.g. for automatically building mods with every commit & pull request.

I say hell yes.

**Comment by TheMysteriousVincent** [comment]
TravisCI support added with 6062f80cd73d99facaab3aff97c0b22d32b4f853.
@Saborknight Now you just have to create a TravisCI account and add this repository to it.

**Comment by Saborknight** [comment]
Will do, working in that now.

**Comment by Saborknight** [comment]
TravisCI account created, repo enabled
