### ISSUE TITLE
9Liner Medevac Request form inaccuracies

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#15]
As per the comment on Steam Workshop by "Merco CroCop":

> Sir! Life 5 of the medevac request, A-Ambulatory, L-Litter!!!!!!

As it turns out, the selected Medevac form for this mod had a slight inaccuracy with line 5: Number of Patients.
Where it currently states **A-Litter** and **B-Ambulatory** it should actually read **A-Ambulatory** **L-Litter** **E-Escort**. These make more sense with their letter designation anyway.

See examples from:
1. http://blog.refactortactical.com/blog/how-to-call-in-a-9line-medevac-and-mist-report/
1. http://slideplayer.com/slide/4511099/15/images/6/MEDIVAC+REQUEST+FORM+GTA+08-01-004.jpg

Ideally, as described in the second link, there would be blank areas to write the number of each type.

**Comment by TheMysteriousVincent** [comment]
Fixed medevac nineliner to A, L and E with c2eb605bc3c044ea4863b3a4895694941a261af6
