### ISSUE TITLE
Add onKeyUp saving

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#16]
Feature request:
Each time a player types something on a sheet it should be automatically saved, so that the save button is optional.

**Comment by Saborknight** [comment]
How much of a performance cost would this have?

**Comment by TheMysteriousVincent** [comment]
Each time saving needs the following amount of time:
```
Result:
0.0748 ms

Cycles:
10000/10000

Code:
call nln_adjust_fire_mission_fnc_savePage;
```

For the medevac nineliner:
```
Result:
0.108155 ms

Cycles:
9246/10000

Code:
call nln_medevac_nineliner_fnc_savePage;
```

And for the noteblock:
```
Result:
0.108155 ms

Cycles:
9246/10000

Code:
call nln_medevac_nineliner_fnc_savePage;
```

**Comment by Saborknight** [comment]
Use a keybind like Ctrl+S instead. Keep the "Save" button on there though (for those who don't know about the keybind)!

**Comment by TheMysteriousVincent** [comment]
Although it might be helpful if the page got saved if the player clicks on a previous or next button (except from new ones).

**Comment by Saborknight** [comment]
Agreed, so couldn't we just group that under an eventhandler which listens for a `pageClosing(_type, _id, _value)` and then save the page? Then we would only have to worry about a Keybinding to save it is pressed, the save button is clicked or the page is closed.

**Comment by TheMysteriousVincent** [comment]
Good idea, I like it. I just saw that I already implemented this like here: https://github.com/Saborknight/9liners-and-notepad/blob/master/addons/sheets/sheet_cas_nineliner/functions/fn_onUnload.sqf

**Comment by TheMysteriousVincent** [comment]
Done with e9ce6f79cd573a7ae5feda58c2b8e5733d88618c
