### ISSUE TITLE
Coding guidelines

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#17]
If contributors want to contribute code, they should check their code first on this guidelines: https://ace3mod.com/wiki/development/coding-guidelines.html

Except some formal guidelines like the way how if-statements are written. I prefer writing in "big steps":
```sqf
if (true) then
{}
else
{};
```
instead of
```sqf
if (true) then {
} else {
};
```

Although, i would prefer using this kind of template header guideline for scripts: https://github.com/CBATeam/CBA_A3/wiki/Documenting-SQF-functions

Because if we want to document functions, the CBA Team created a tool for documentation generation working with this kind of format.

**Comment by Saborknight** [comment]
You see.. I prefer the opposite. In my mind, all symbols related to commands should be on the same line... But that's just me.

**Comment by TheMysteriousVincent** [comment]
Its more important that the ACE guidelines of how to write performance friendly code are respected.

**Comment by TheMysteriousVincent** [comment]
Added to the Wiki: https://github.com/Saborknight/9liners-and-notepad/wiki/Coding-guidelines
