### ISSUE TITLE
Create Christmas edition

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#18]
Lets style the things in time for christmas!

And lets make it a separate git branch so that we can come back to it next year. Unless a better reversible way is suggested.

**Comment by TheMysteriousVincent** [comment]
medevac nineliner added with c2eb605bc3c044ea4863b3a4895694941a261af6

**Comment by Saborknight** [comment]
Rather than messing with separate branches on git for this, lets just store event specific data in a directory "events"

**Comment by TheMysteriousVincent** [comment]
Well thats a good idea!

**Comment by Saborknight** [comment]
This has been completed with c4ac97a.
