### ISSUE TITLE
Integrate ACE Interaction for selection of pages

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#2]
Integrate ACE Interaction for selection of the formatted pages. This should provide a second, more fluid method of navigation than #1.

---

**Source**: [BI Forums](https://forums.bistudio.com/forums/topic/178540-ingame-9liners-notepad/?do=findComment&comment=2839202)

> A suggestion:
> One Key to open a menu (como rose style or something alike) while pressed in wich you can choose to open available sheets (of wich you have the items).

**Submitted by** [Ian Bones](https://forums.bistudio.com/profile/871280-ian-bones/)

**Comment by TheMysteriousVincent** [comment]
So the sheets should be displayed like this, right?
```
Self-Interaction /
    Sheets /
        CAS nineliner
        MEDEVAC nineliner
        [...]
```

**Comment by Saborknight** [comment]
Yes... I'm trying to think of a word more descriptive than just "Sheets" though... "Pages" maybe rather? But yes, that would be the ideal structure.

Also, I think implementing that when the ACE interaction key is pressed, and only if controls are disabled still, the page is closed. Much like what happens when you're doing something in ACE and you get that loading bar telling you how long the interaction still has until completion and then you press the ACE interact key before it is completed. The action is cancelled and the loading bar disappears.

This should not apply when ACE is not an enabled mod (obviously) or when controls are already enabled (so let the player interact with ACE whilst the sheet is still open next to them)

**Comment by TheMysteriousVincent** [comment]
Idea of the ACE interaction menu:
![arma 3 screenshot 2017 12 15 - 15 01 42 99](https://user-images.githubusercontent.com/10392626/34045408-0f8d155c-e1a9-11e7-9b7b-972fc16161fb.png)

**Comment by Saborknight** [comment]
Nice, if you select just the sheet as opposed to one of the sub-options, does it do anything? I'd have thought it be best for that to use the default "edit" option. Also, the "hide" option shouldn't be showing when that sheet isn't actually selected yet.

But yes, cool!

**Comment by TheMysteriousVincent** [comment]
ACE interactions might be a part of the sheet template in #19.
