### ISSUE TITLE
Add Japanese translations - Kuzira

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#23]
Japanese translations to make it into v1.0? Yes please!

**Comment by TheMysteriousVincent** [comment]
Japanese documentation added with a1cdfbf33c0a243c790d582999eed6c17b375d32 for now.

**Comment by Saborknight** [comment]
A fix has been added with b2d0ff611f72481387abf5c3570fc1fb8ca1efe6
