### ISSUE TITLE
Add fonts to use in sheets

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#25]
We shall add fonts to sheets, so that users can choose between different fonts, like handwriting fonts, e.g.

**Comment by TheMysteriousVincent** [comment]
* font added `SegoeScript`
* font added `DomesticManners`

any other suggestions?

**Comment by Saborknight** [comment]
This was completed with abe173cbfc199872d47a20268bd35842cfcba83a already. Continued enhancement of fonts can be referred to #26.
