### ISSUE TITLE
Add font settings for each page

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#26]
Like in #25 mentioned, we should add different fonts.
But to have the wanted effect (like in multiplayer by sharing sheets), we need to add a new array index for just the font name.
Default would be `TahomaB`, I think.
This will be in the format like this for every savable page:
`[profileName, "SegoeScript", ....]`

**Comment by TheMysteriousVincent** [comment]
The font setting was added a few months ago.

**Comment by Saborknight** [comment]
After some deliberation, it's seeming like a better idea to act as if the fonts that are chosen by the user should be how the sheets display to the user no matter the situation. To this end, the extra item in the array for the font should be removed and all sheets and pages should display the font chosen in the user's settings.

Essentially, a font is chosen, and all notes are displayed in that font regardless of circumstance. That is, after all, what the setting seems like it's supposed to do anyway.
