### ISSUE TITLE
Undefined font related variable throwing errors on page save

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#30]
**Description:**
One of these occurs when a page is being saved:
- Undefined variable "nln_ui_fonts_defaultfont" in file addons\gunship_cff\functions\fn_savePage.sqf [nln_gunship_cff_fnc_savepage] on line 5
- Undefined variable "nln_ui_fonts_defaultfont" in file addons\notepad\functions\fn_savePage.sqf [nln_notepad_fnc_savepage] on line 5
- Undefined variable "nln_ui_fonts_currentfont" in file addons\marking_mission\functions\fn_updateMenu.sqf [nln_marking_mission_fnc_updateMenu] on line 20
- Undefined variable "nln_ui_fonts_currentfont" in file addons\gunship_cff\functions\fn_updateMenu.sqf [nln_gunship_cff_fnc_updateMenu] on line 20
The two fonts embedded with the mod aren't activating in-game, most likely due to these undefined variables.

**Steps to reproduce:**
- Open any sheet
- Click save, or move to another page (which will also invoke a page save)

**Comment by Saborknight** [comment]
RPT log for the relevant error (using a different sheet though):
```
14:50:09 Error in expression <ui displayCtrl (1399 + _i)) ctrlSetFont nln_ui_fonts_currentFont;
};

private _s>
14:50:09   Error position: <nln_ui_fonts_currentFont;
};

private _s>
14:50:09   Error Undefined variable in expression: nln_ui_fonts_currentfont
14:50:09 File \x\nln\addons\marking_mission\functions\fn_updateMenu.sqf [nln_marking_mission_fnc_updateMenu], line 20
```

**Comment by TheMysteriousVincent** [comment]
The file is called after the PreInit, right? - Or the error occurs after the PreInit, right?

**Comment by Saborknight** [comment]
[Arma3_x64_2018-07-22_14-17-05.zip](https://github.com/Saborknight/9liners-and-notepad/files/2224751/Arma3_x64_2018-07-22_14-17-05.zip)

Here's the complete RPT. It occured whenever I tried to save, change page... and I can't remember when else. I'll go through the actions again and actually document what errored when.

**Comment by TheMysteriousVincent** [comment]
Should be fixed now if packed with Makefile on Linux Systems

**Comment by Saborknight** [comment]
Alright, I'll sort my local makefile out. I've been getting some errors in the file itself, so it may very well be that I'll need to make a `makefile.windows` as you suggested in PMs
