### ISSUE TITLE
ACE individual sheet should have default interact

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#36]
**Description:**
- ACE interactions should have a default if you interact with the sheet parent menu item. This means one less thing to try and aim for when self interacting for the sheets.

**Comment by TheMysteriousVincent** [comment]
And what action should be the default? Show the sheet?

**Comment by Saborknight** [comment]
Edit the sheet should be the default, in my opinion

**Comment by Saborknight** [comment]
Done in 6ce7ba9
