### ISSUE TITLE
Click away from sheet to re-enable controls (re-instate functionality from v0.3.1)

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#39]
**Description:**
Bring back the old functionality, where by clicking away from the currently interactive sheet re-enables controls. This is useful during an emergency, even though tapping the ESC key does work, there's no harm in re-implementing this.

**Comment by TheMysteriousVincent** [comment]
So you mean that active sheets can moved to the background while clicking outside the sheet itself?

**Comment by Saborknight** [comment]
Exactly. It seems to me to be an intuitive action. Having said that, I have been playing with 9 Liners mod for years now.. xD

**Comment by TheMysteriousVincent** [comment]
Should be no problem.

**Comment by Saborknight** [comment]
Thanks for this. How come you've made the control half the size of the safearea?
Also, I've found that displays `onMouseDown` kept giving a false mouse position. I would assume the same to happen `onMouseUp`. But we can find the real mouse position with this: `getMousePosition`, which I have found works very precisely.

**Comment by Saborknight** [comment]
My bad, didn't realise you were intending for that control to be demonstrative only

**Comment by Saborknight** [comment]
Done in c5aee1c.
**Note:** There is no tooltip to tell the user what to do, but left click enables controls and right click closes the sheet entirely. This happens regardless of what the setting `nln_dialogToDisplay_enable` is set to.
