### ISSUE TITLE
Notepad "Close" button doesn't function as it seems it should

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#41]
**Description:**
- Notepad "Close" button doesn't actually close the sheet, but it does re-enable the controls. I am aware that this is caused by my default setting of having the sheets stay there until I explicitly hide them, however that little blue "Close" label at the bottom right of the notepad is therefore misleading. Change it to "Finished" or something less explicit about the action which will occur, to allow for closing or re-enabling controls without specifically specifying?

**Comment by Saborknight** [comment]
@TheMysteriousVincent what do you think? Replace the button of "Close" with some other word, or just override the default for that one sheet and close it regardless.

I'm on the side of changing the button label itself (not the functionality)

**Comment by TheMysteriousVincent** [comment]
I agree with you. But we also could add a setting to manually change the closing behaviour for every single sheet.

**Comment by Saborknight** [comment]
That is an interesting suggestion, but I wonder if it might add too much complexity  to have it for every sheet... :/
Nah, I think eliminate that "Close" button on the Notepad sheet and depend on the use of the ESC key for now. If we receive feedback in the future pointing to its requirement, then we can implement a button performing the same functionality as the ESC key when it comes to it.

**Comment by Saborknight** [comment]
Done in e131b98
