### ISSUE TITLE
Codacy Badges

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#46]
N think there is no neeed to use Codacy here in this project because Codacy does not support the main language SQF.

Currently Codacy just checks .cpp, .py and .xml files but C++ is not the language used in .cpp-files.
Its simply because there is no such "good" interpreter for config- and SQF-files.

**Comment by Saborknight** [comment]
Hehe, awww, don't like seeing a nice great green "A" on our readme? xD

I'll rid us of it tonight

**Comment by TheMysteriousVincent** [comment]
@Saborknight Thats not the point - I like it too, but at the same time I think that this is not necessary if there is no practical function.

**Comment by Saborknight** [comment]
I know I know, I did understand your point and it makes sense. The only thing it is actually rating are the python scripts, which actually give a false indication to any visitor who probably expects the badge to be in relation to the entire project.

**Comment by Saborknight** [comment]
Removed in the commit mentioned above
