### ISSUE TITLE
Provide capability for translations to be added

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#5]
Need to internationalise the mod so that people can add their own localisations of the strings in the mod.

**Comment by TheMysteriousVincent** [comment]
I would do that for German / English translation.

**Comment by TheMysteriousVincent** [comment]
Localization is now able to merge. See #11.

**Comment by Saborknight** [comment]
As per commits 708daf4 and 61d512b, localisations for "main" files have been implemented.

**Comment by Saborknight** [comment]
Final commit, all strings now localized/translation capable
