### ISSUE TITLE
Create Build script for Building and Publishing/Release

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/9liners-and-notepad#6]
The build system should have as few dependencies as possible, easy to use, and output as much debugging as possible. It should:

- [x] For Release only: Edit version numbers wherever they are referenced.
- [x] Generate private/public key pair with version included in the name -> copy public key into `root/key` for the servers
- [x] Pack each subdirectory of the addons directory into PBOs. For Releases -> binarising all possible assets + signing PBOs
- [x] Copy across any other supporting assets for the presentation/description of the mod on the Steam Workshop

**Comment by TheMysteriousVincent** [comment]
In addtion to the private key, we probably should create a new private / public key-pair every release.

**Comment by TheMysteriousVincent** [comment]
Maybe we should also you something like TravisCI, e.g. for automatically building mods with every commit & pull request.

**Comment by Saborknight** [comment]
Completed with the last commit referencing this issue (look up one issue log message).
