### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#8]
It is (maybe) neccessary to add a license so that other people know what their rights to use this addons are.
I recommend something like the MIT or GNU v3.0 license.

**Comment by Saborknight** [comment]
If you have a look at the readme, you'll notice that there does exist a licence. This has carried over from the original author, which is why I do not feel inclined to change it. Is there a problem with the currently used licence?

**Comment by TheMysteriousVincent** [comment]
Nope there isn't any problem. I didn't read the readme. But I would recommend moving that License to a `LICENSE` file in my next pull request, so that it is more GitHub likely.

**Comment by TheMysteriousVincent** [comment]
License added with 0a752944ffbfd2f28caf01f02ba9dc9b48227330
