### ISSUE TITLE
Add a more dynamic page system

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#9]
Feature request:
Wouldn't it be nice if there were nearly unlimited pages in this documents?

Why isn't that implemented? Any reasons for that?

Of course if there were unlimited pages it would be a kind of unorganized stack, but what is against this:
There are just as many pages as there were added into the system.
So you can simplify the current static saving as scripted here: https://github.com/Saborknight/9liners-and-notepad/blob/master/addons/cw_nineliner_and_notepad/Data/updateVersion.sqf

What do you think @Saborknight ?

**Comment by TheMysteriousVincent** [comment]
Additionally: Why exactly got the items removed?

**Comment by Saborknight** [comment]
I think that the method of storing the sheets could definitely be more centralised. Something to work on for sure.

Items were removed in v0.3 by the original author so that this mod could remain a client-side mod, a sentiment I very much agree with.
Reference [this](https://forums.bistudio.com/forums/topic/178540-ingame-9liners-notepad/?do=findComment&comment=2807631) and [this](https://forums.bistudio.com/forums/topic/178540-ingame-9liners-notepad/?do=findComment&comment=2807581).

**Comment by TheMysteriousVincent** [comment]
For the implementation it may will be neccessary to abstract the way of saving pages.
I recommend the following idea:

We've got as much arrays we need to cover every dialog. Each array is a CBA_hash format, where we easily can set an number id for each page.

For example a variable storing the contents:
```sqf
nln_sheet_cas_nineliner = ([[], []] call CBA_fnc_hashCreate);
```

Additionally, we have to add static string types for each sheet (like `cas_nineliner` e.g.) to seperate sheet values from each other.
A function to add any type of page:
```sqf

params [
    ["_type", "", [""]],
    ["_values", [], [[]]]
];

//nln_availableTypes = all available page/sheet types

if !(_type in nln_availableTypes) exitWith { false; };
if ((count _values) <= 0) exitWith { false; };

private _namespaceVar = (format["nln_pages_%1", _type]);
private _hash = (profileNamespace getVariable [_namespaceVar, []]);

if !([_hash] call CBA_fnc_isHash) exitWith {};

private _keys = ([_hash] call CBA_fnc_hashKeys);

private _id = -1;
while
{
    (_id <= -1)
}
do
{
    _id = _id + 1;
    if !(_id in _keys) exitWith {};
};

profileNamespace setVariable [_namespaceVar, ([_hash, _id, _values] call CBA_fnc_hashSet)];
//maybe save. But its slow as hell! -> saveProfileNamespace;
true;
```

**Comment by Saborknight** [comment]
Completed by @TheMysteriousVincent as per 6e51ead
